# This is a basic workflow that is manually triggered

name: Leebyte.net Create Community Redirect

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      id:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'ID of Redirect'
        # Default value if no value is explicitly provided
        default: 'Short-ID'
        # Input has to be provided for the workflow to run
        required: true
      url:
        description: 'URL of Redirect'
        default: 'https://'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ccdir"
  ccdir:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Create Redirect
      #working-directory: ./c/${{ github.event.inputs.id }}
      run: |
        mkdir c
        cd c
        echo "Creating Redirect ID: ${{ github.event.inputs.id }}"
        mkdir ${{ github.event.inputs.id }}
        cd ${{ github.event.inputs.id }}
        echo "Creating Redirect URL: ${{ github.event.inputs.url }}"
        touch index.html
        echo "<meta http-equiv="refresh" content="0; url='${{ github.event.inputs.url }}'" />" > index.html
        echo "Finished Creating New Redirect!"
        ls -1
